import { motion } from 'framer-motion';
import { HelpCircle } from 'lucide-react';

const QAItem = ({ question, answer }) => (
  <div className="bg-white dark:bg-slate-900 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 hover:border-blue-400 dark:hover:border-blue-500 transition-colors">
    <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-100 flex items-start gap-3 mb-3">
      <HelpCircle className="w-6 h-6 text-blue-500 shrink-0 mt-0.5" />
      {question}
    </h3>
    <div className="text-slate-600 dark:text-slate-300 ml-9 leading-relaxed">
      {answer}
    </div>
  </div>
);

const InterviewQA = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ duration: 0.3 }}
      className="max-w-4xl space-y-12 pb-12"
    >
      <div className="border-b border-slate-200 dark:border-slate-800 pb-6">
        <h1 className="text-4xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-500 mb-4">
          Docker Interview Questions
        </h1>
        <p className="text-xl text-slate-600 dark:text-slate-400 leading-relaxed">
          Prepare for your next DevOps or Software Engineering interview with these curated Docker questions categorized by difficulty.
        </p>
      </div>

      {/* Easy Section */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold text-emerald-600 dark:text-emerald-400 border-b border-slate-200 dark:border-slate-700 pb-2 flex items-center gap-2">
          <span>🟢</span> Easy
        </h2>
        <div className="space-y-4">
          <QAItem 
            question="What is Docker and why is it used?"
            answer="Docker is a platform that uses OS-level virtualization to deliver software in packages called containers. It is used to simplify deployment, ensure consistency across environments, and improve resource efficiency compared to traditional virtual machines."
          />
          <QAItem 
            question="What is the difference between a Docker image and a Docker container?"
            answer="An image is a read-only template containing the application code, libraries, and dependencies. A container is a running instance of an image."
          />
          <QAItem 
            question="What is a Dockerfile?"
            answer="A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image. It automates the image creation process."
          />
          <QAItem 
            question="What is Docker Hub?"
            answer="Docker Hub is a cloud-based registry service where developers can push and pull Docker images. It acts as a central repository for sharing containerized applications."
          />
        </div>
      </section>

      {/* Medium Section */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold text-amber-500 dark:text-amber-400 border-b border-slate-200 dark:border-slate-700 pb-2 flex items-center gap-2">
          <span>🟡</span> Medium
        </h2>
        <div className="space-y-4">
          <QAItem 
            question="How is a Docker container different from a Virtual Machine?"
            answer="VMs include a full guest operating system and virtualized hardware, making them heavy. Containers share the host OS kernel and isolate processes, making them lightweight, faster to start, and less resource-intensive."
          />
          <QAItem 
            question="Explain Docker Compose and its use case."
            answer="Docker Compose is a tool for defining and running multi-container Docker applications. It uses a YAML file to configure the application's services, networks, and volumes, making it easy to spin up complex environments with a single command."
          />
          <QAItem 
            question="What are Docker Volumes?"
            answer="Docker Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. Unlike the container's writable layer, volumes are managed directly by Docker, bypass the union file system, and can be shared safely among multiple containers."
          />
          <QAItem 
            question="What is the difference between 'COPY' and 'ADD' in a Dockerfile?"
            answer="Both copy files from the host to the image. However, 'ADD' has extra features: it can extract local tar files automatically and can download files from remote URLs. 'COPY' is preferred for simple local file transfers due to better predictability."
          />
        </div>
      </section>

      {/* Hard Section */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold text-red-500 dark:text-red-400 border-b border-slate-200 dark:border-slate-700 pb-2 flex items-center gap-2">
          <span>🔴</span> Hard
        </h2>
        <div className="space-y-4">
          <QAItem 
            question="What are Docker namespaces and cgroups?"
            answer="Namespaces provide isolation for containers (e.g., PID, networking, mount points), ensuring a container cannot see processes outside it. Control Groups (cgroups) limit and isolate the resource usage (CPU, memory, disk I/O) of a collection of processes."
          />
          <QAItem 
            question="Explain the concept of Docker Multi-stage builds and why they are useful."
            answer="Multi-stage builds allow you to use multiple FROM statements in a single Dockerfile. Each FROM instruction begins a new stage. You can selectively copy artifacts from one stage to another, leaving behind everything you don't want in the final image. This significantly reduces the final image size and improves security by omitting build tools."
          />
          <QAItem 
            question="How does Docker handle networking internally?"
            answer="Docker creates a default bridge network (docker0) when installed. Containers attached to this network can communicate via IP addresses. Docker also provides an embedded DNS server so containers on user-defined networks can resolve each other by container name. For external communication, it uses NAT (Network Address Translation)."
          />
          <QAItem 
            question="What is the difference between an Entrypoint and a CMD?"
            answer="CMD sets default commands and/or parameters that can be easily overridden from the command line when running 'docker run'. ENTRYPOINT configures a container that will run as an executable. Command-line arguments passed to 'docker run' are appended to the ENTRYPOINT command instead of overriding it (unless --entrypoint is explicitly used)."
          />
        </div>
      </section>
    </motion.div>
  );
};

export default InterviewQA;
